version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install bandit flask
  build:
    commands:
      - echo "Starting Advanced Security Policy Audit..."
      # This 'grep' only looks for lines that START with ADMIN_PASSWORD
      # It will IGNORE lines that start with '#'
      - |
        if grep -q -E "^\s*ADMIN_PASSWORD\s*=" secure_app/app.py; then
          echo "VULNERABILITY FOUND! Terminating Build..."
          exit 1
        else
          echo "No active hardcoded credentials found. System Secure."
        fi
      - bandit -r . -lll
artifacts:
  files:
    - "**/*"